spring:
  kafka:
    properties:
      bootstrap-servers: localhost:9092
  cloud:
    stream:
      function:
        definition: produceChuckNoris;consumeChuckNoris;processWords
        bindings:
          processWords-in-0: chuckfacts
          processWords-out-0: counts
      bindings:
        produceChuckNoris-out-0:
          binder: kafka
          destination: chuckfacts
          producer:
            partitionCount: 2
        consumeChuckNoris-in-0:
          binder: kafka
          destination: chuckfacts
          group: kotlinFactsOutputter
      kafka:
        binder:
          consumer-properties:
            key.serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
            value.serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
          producer-properties:
            key.serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
            value.serializer: org.springframework.kafka.support.serializer.StringOrBytesSerializer
          auto-create-topics: true
        streams:
          binder:
            application-id: chuck-norris-word-count
            configuration:
              default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
              default.value.serde: org.apache.kafka.common.serialization.Serdes$BytesSerde
              commit.interval.ms: 1000


